name: ci
on:
  push:
    branches: [main]

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: rustup show
        run: rustup show
      - name: install components
        run: rustup component add clippy rustfmt
      - name: install nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest
      - name: format check
        run: cargo fmt --all -- --check
      - name: test
        run: cargo nextest run
