name: ci
on:
  push:
    branches: [main]

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v19
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - name: format check
        run: nix develop -c cargo fmt --all -- --check
      - name: test
        run: nix develop -c cargo nextest run
