name: Release PR (version bump)

on:
  workflow_dispatch:
    inputs:
      level:
        type: string
        default: patch
        required: false

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v19
      - uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Install cargo-release
        run: nix develop -c cargo install cargo-release --locked

      - name: Configure git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Bump version
        shell: bash
        run: |
          set -euo pipefail
          LEVEL="${{ github.event.inputs.level }}"

          nix develop -c cargo release version --execute --no-confirm "$LEVEL"
          PKG_VER="$(sed -n 's/^version *= *"\(.*\)"/\1/p' Cargo.toml | head -n1)"
          echo $PKG_VER

          git checkout -b "release/${PKG_VER}"
          nix develop -c cargo release commit --execute --no-confirm

          git push -u origin HEAD

          gh pr create --fill
          # gh pr merge --squash --delete-branch
