name: Release PR (version bump)

on:
  workflow_dispatch:
    inputs:
      level:
        type: string
        default: patch
        required: false

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - uses: actions/checkout@v4
      - name: install components
        run: rustup component add clippy rustfmt

      - name: Install cargo-release
        run: cargo install cargo-release --locked

      - name: Configure git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Bump version
        shell: bash
        run: |
          set -euo pipefail
          LEVEL="${{ github.event.inputs.level }}"

          cargo release version --execute --no-confirm "$LEVEL"
          PKG_VER="$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].version')"
          echo $PKG_VER

          git checkout -b "release/${PKG_VER}"
          cargo release commit --execute --no-confirm

          git push -u origin HEAD

          gh pr create --fill
